### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Marting2105** [Arqaen/Footlocker-Releases#1]
Hey, 
Here is what I got when I start the bot 
![image](https://user-images.githubusercontent.com/97480952/201397166-240f3820-3d0a-42d1-8b77-28a78fae790a.png)

**Comment by Arqaen** [comment]
@Marting2105 Update to the last version of the repo, the error has been solved, the problem was the headers.

**Comment by Marting2105** [comment]
Thanks,
But I still have the error

**Comment by Arqaen** [comment]
@Marting2105  Can you give more details? did you edit the config file and update the repo? The code its working, i just checked.

**Comment by Marting2105** [comment]
Yes I did

**Comment by Marting2105** [comment]
I downloaded all the stuff and edited the config file

**Comment by Arqaen** [comment]
Make `git pull` if you havent made yet, the last version also provides more information about the errors.

**Comment by Marting2105** [comment]
I cloned again the repo, donc "git pull" to be sure, did the config, but still have "error"

**Comment by Marting2105** [comment]
Are you sure I don't have to install a package before lauching it ?

**Comment by Arqaen** [comment]
Yes, you need requests library, its specified in the readme, just make `pip install -r requirements.txt` also update again and see if you get more information in the errors.

**Comment by Marting2105** [comment]
Yeah, done it too but got error. Are you sure we don't need other library ?

**Comment by Arqaen** [comment]
Doesnt need more libraries, i'll need more information to help you, for what country are you trying to get the data?

**Comment by Marting2105** [comment]
I tried with default country and all country (fr, nl, be, es, pl, de, ...) but nothing works

**Comment by Arqaen** [comment]
Update to the last version and tell me what status code you get

**Comment by Marting2105** [comment]
I just get "error"
![image](https://user-images.githubusercontent.com/97480952/201498719-0d4532f0-3884-401b-96f1-04408f18f39d.png)

**Comment by Marting2105** [comment]
![image](https://user-images.githubusercontent.com/97480952/201498728-8056668d-0ae2-4e77-83c3-29d5c7d1e596.png)
all files are the latests ones

**Comment by Arqaen** [comment]
I just made a new commit, try with that

**Comment by Marting2105** [comment]
Thanks, updated

**Comment by Marting2105** [comment]
![image](https://user-images.githubusercontent.com/97480952/201498777-daabde50-9ed7-4191-bc31-33c3911edf80.png)
have this error now

**Comment by Arqaen** [comment]
The server its rejecting your conection, maybe is your ip, can you try with the browser?
https://www.footlocker.de/apigate/release-calendar

**Comment by Marting2105** [comment]
I can see the site

**Comment by Marting2105** [comment]
![image](https://user-images.githubusercontent.com/97480952/201499269-f68e7bd1-af8b-4eca-98f2-c64967463bdf.png)

**Comment by Arqaen** [comment]
if you didnt edit the code, i cant explain whats wrong, try with other pc if you can, its working fine for me

**Comment by Marting2105** [comment]
I tryied with an other pc, don't understand what's wrong

**Comment by Arqaen** [comment]
Ey @Marting2105 , sorry for the delay, can you try now? i did a new update and should be fixed, it was the antibot...

**Comment by Marting2105** [comment]
Hey, 

it works, thanks

**Comment by Marting2105** [comment]
How can I get the "manufacturerSku" displayed in the webhook ?

**Comment by Arqaen** [comment]
Declare a new variable, and add that data to the variable info

**Comment by Marting2105** [comment]
Thanks for your answer.
Would you mind offering me this new line of code. I tried but it gives me an error. You are surely more qualified than me to do it 😁

**Comment by Arqaen** [comment]
**Try this:**
Add this in line 90
```
man = release['manufacturerSku']
```


Replace line 99 with this
```
"description" : f"**Name**: {name}\n**Brand**: {brand}\n**Gender**: {gender}\n**manufacturerSku**: {man}\n**Id**: {id}\n\n**Launch**: {launch}\n"
```

**Comment by Marting2105** [comment]
Thanks,
here is the error
![image](https://user-images.githubusercontent.com/97480952/204323846-d53a549c-b272-40e8-a371-2b1a23e8311b.png)

**Comment by Arqaen** [comment]
You are making any mistake, shouldnt appear any error
